wecloudproject:
  outputs:
    dev:
      account: KNMBTVZ-XV29264
      database: TPCDS
      password: neTeeru^19860^
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: KALYANQSQL
      warehouse: WCD_PRJ
  target: dev
